version: "3.2"
services:
  mysql_alpha:
    container_name: alpha    
    hostname: alpha 
    image: mysql:latest
    ports:
      - 8083:3306
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
  
  mysql_beta:
    container_name: beta
    hostname: beta
    image: mysql:latest
    ports:
      - 8082:3306
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  engine:
    build: engine
    depends_on:
      - mysql_alpha
    links:
      - mysql_alpha
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    environment:
      PYTHONUNBUFFERED: 1
    command: ["./wait_for_mysql.sh", "mysql_alpha", "3306", "qwerty", "root", "flask run --host=0.0.0.0"]
